In [1]:
#Create a 3×3 array filled with random numbers and print its shape.
# Convert an array of floats [1.1, 2.2, 3.3] into integers.
# Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
# Reshape a 1D array of size 9 into a 3×3 matrix.
# Use boolean masking to filter numbers greater than 50 in an array.

In [16]:
#Create a 3×3 array filled with random numbers and print its shape.
import numpy as np
import random

random_array = np.random.randint(1, 100,(3,3))
print(random_array)
   

    


[[46 65 19]
 [61 30 96]
 [25 77 80]]


In [18]:
# Convert an array of floats [1.1, 2.2, 3.3] into integers.
import numpy as np
array=np.array([1.1,2.2,3.3])
int_arr= array.astype(np.int32)
print(int_arr)


[1 2 3]


In [19]:
# Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
array=np.array([1,2,3,4,5,6])
ind=[1,3,5]
print(array[ind])


[2 4 6]


In [20]:
# Reshape a 1D array of size 9 into a 3×3 matrix.
array=np.array([1,1,1,1,1,1,1,1,1])
reshape= array.reshape((3,3))
print(reshape)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [21]:
# Use boolean masking to filter numbers greater than 50 in an array.
import numpy as np
array=np.array([12,45,68,98,87,57,67,32])
print(array[array>50])

[68 98 87 57 67]


In [3]:
import numpy as np
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D)  
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
[[1 2 3]
 [7 8 9]]


In [ ]:
# NumPy’s data types and how they affect memory usage and performance in ur arrays.

# 1. Introduction to NumPy Data Types
# NumPy arrays are homogeneous, meaning that they can only store elements of the same type. This is different from Python lists, which can hold mixed data types. NumPy supports various data types (also called dtypes), and understanding them is crucial for optimizing memory usage and performance.

# Common Data Types in NumPy:
# int32, int64: Integer types with different bit sizes.
# float32, float64: Floating-point types with different precision.
# bool: Boolean data type.
# complex64, complex128: Complex number types.
# object: For storing objects (e.g., Python objects, strings).
# You can check the dtype of a NumPy array using the .dtype attribute.

In [10]:
#np benefits (vectorisation,broadcasting,application(hands-on)
#simple py method 
import numpy as np
arr=np.array([1,2,3,4,5])
result =[]
for num in arr:
    result.append(num**2)
    print(result)
#vectorisation(fixes loop problen,optimizes low level C backend,processes multiple elements in parallel)
result = arr**2
print(result)

[1]
[1, 4]
[1, 4, 9]
[1, 4, 9, 16]
[1, 4, 9, 16, 25]
[ 1  4  9 16 25]


In [11]:
#broadcasting(array and scalar operations)
arr = np.array([1,2,3,4,5])
result = arr+10
print(result)
#with different arrays and shapes(rules:compatible dimension,streching arrays)
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2,3])
result = arr1+arr2
print(result)

[11 12 13 14 15]
[[2 4 6]
 [5 7 9]]


In [12]:
#Normalizing Data Using Broadcasting((data-mean)-std)
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,12,14],[3,22,14]])
#calculating mean and standard deviation for each feature(column)
mean=data.mean(axis=0)
std=data.std(axis=0)
#normalise
normalized_data=(data - mean)/std
print(normalized_data)

[[-1.26491106 -1.12396131 -1.42387716]
 [-0.31622777 -0.6916685  -0.73490434]
 [ 0.63245553 -0.25937569 -0.04593152]
 [ 1.58113883  0.31701473  1.10235651]
 [-0.63245553  1.75799077  1.10235651]]


In [21]:
#mathematical functions in numpy
import numpy as np
arr = np.array([1,2,3,4,5])
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))#Compute the variance of an array.
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.prod(arr))
print(np.median(arr))
print(np.percentile(arr, 50))  # For the 50th percentile (median)
print(np.argmin(arr))#– Return the index of the minimum value in an array.
print(np.argmax(arr))#– Return the index of the maximum value in an array.
print(np.corrcoef(arr)) #– Compute the correlation coefficient matrix of two arrays.
print(np.unique(arr))#Find the unique elements of an array.
print(np.diff(arr))#– Compute the n-th differences of an array.
print(np.cumsum(arr))# – Compute the cumulative sum of an array
print(np.linspace(0, 10, 5))  # 5 numbers from 0 to 10...– Create an array with evenly spaced numbers over a specified interval.
print(np.log(arr))#– Compute the natural logarithm of an array.
print(np.exp(arr))#– Compute the exponential of an array.

3.0
1.4142135623730951
2.0
1
5
15
120
3.0
3.0
0
4
1.0
[1 2 3 4 5]
[1 1 1 1]
[ 1  3  6 10 15]
[ 0.   2.5  5.   7.5 10. ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [1]:
cant remember such stupid shit
## to get input from an nxm array
#find n and m
n = int(input("Enter number of rows (n): "))
m = int(input("Enter number of columns (m): "))
#get elements entered
array = []
print("Enter the elements row-wise:")
for i in range(n):
    row = list(map(int, input().split()))
    if len(row) != m:
        print("Please enter", m, "elements.")
        exit()
    array.append(row)

print("Your array:")
for row in array:
    print(row)


Enter number of rows (n):  2
Enter number of columns (m):  2


Enter the elements row-wise:


 5 6
 3 4


Your array:
[5, 6]
[3, 4]
